apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-deployment
  labels:
    app: gym
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gym
  template:
    metadata:
      labels:
        app: gym
    spec:
      containers:
      - name: gym
        image: docker.io/jndansi/gym:latest
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: gym-service
spec:
  selector:
    app: gym
  type: ClusterIP
  ports:
  - name: gym
    protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30021
    # # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # # you can specify a value in the `spec.ports[*].nodePort` field.
